from typing import Any, Dict, List, Optional
from pandas.core.frame import DataFrame
from selenium.webdriver.remote.webdriver import WebDriver
from selenium.webdriver.remote.webelement import WebElement

from stubs.common import User, DatePack, CssSelector

class Crawler:
    login_url: str
    redirect_url: str
    driver: WebDriver
    dates: DatePack
    dir_path: str
    user: User
    css: Dict[str, str]
    req_advertise_info:bool = False
    def __init__(self, user: User, year: str, month: str, req_advertise_info:bool = False, chrome_debug:bool = False) -> None: ...
    @staticmethod
    def fix_calendar(start_calendar_component: WebElement, year_int: int, month_int: int) -> None: ...
    def parsing_table(self, max_page: int) -> List[List[str]]: ...
    def filtering(self) -> None: ...
    def click_day_in_calendar(self, calendar_btn: WebElement, day_root: CssSelector, click_date: str) -> None: ...
    def collect_data(self) -> DataFrame: ...
    def advertise_traverse(self) -> None: ...
    def go(self) -> DataFrame: ...
