from numpy.core.shape_base import block as block
from re import split as split
from selenium.webdriver.remote.webdriver import WebDriver as WebDriver
from typing import Any

class Crawler:
    login_url: str = ...
    redirect_url: str = ...
    driver: Any = ...
    dates: Any = ...
    dir_path: Any = ...
    user: Any = ...
    css: Any = ...
    req_advertise_info: Any = ...
    def __init__(self, user: Any, year: str=..., month: str=..., req_advertise_info: bool=...) -> None: ...
    @staticmethod
    def fix_calendar(start_calendar_component: Any, year_int: Any, month_int: Any) -> None: ...
    def parsing_table(self, max_page: int=...) -> Any: ...
    def filtering(self): ...
    def click_day_in_calendar(self, calendar_btn: Any, day_root: Any, click_date: Any): ...
    def collect_data(self): ...
    def advertise_traverse(self): ...
    def go(self): ...
