from requests import Session
from typing import Any

class RetrySession(Session):
    __attrs__: Any = ...
    retries: Any = ...
    backoff: Any = ...
    timeout: Any = ...
    set_encoding: Any = ...
    encoding: Any = ...
    def __init__(self, retries: int = ..., backoff: float = ..., timeout: int = ..., **kwargs: Any) -> None: ...
    def request(self, method: Any, url: Any, **kwargs: Any): ...
