from requests import Session
from requests.models import Response
from typing import Any, List, NewType

ResText = NewType('ResText', str)
class RetrySession(Session):
    __attrs__: List[str] = ...
    retries: int = ...
    backoff: float = ...
    timeout: int = ...
    set_encoding: bool = ...
    encoding: str = ...
    def __init__(self, retries: int = ..., backoff: float = ..., timeout: int = ..., **kwargs: Any) -> None: ...
