from pandas.core.frame import DataFrame as DataFrame
from typing import Any

def cleaning(t_df: Any, c_df: Any): ...
def get_stat_by_order(t_df: Any, c_df: Any): ...
def apply_adv_info(df_by_campaign_id: Any, adv_info: Any) -> DataFrame: ...
def get_stat_by_campaign_id(t_df: Any, c_df: Any, adv_info: Any): ...
